"""
gui.mesh_window
================

Visualization window for the triangular FEM mesh generated by
core.mesh_generator.  Displays:
    · Full mesh (triangles filling the complete domain)
    · Domain boundary outline
    · Needle wall hatching
    · Mesh statistics
"""

import numpy as np
import pyqtgraph as pg
from PyQt6.QtWidgets import (QWidget, QVBoxLayout, QHBoxLayout, QLabel,
                             QGroupBox, QFrame)
from PyQt6.QtCore import Qt
from gui.styles import DARK_STYLESHEET
from gui.domain_window import _hatch_rect


class MeshWindow(QWidget):
    """Window that shows the generated FEM mesh."""

    def __init__(self, points, triangles, boundary_edges,
                 polygon, metadata, parent=None):
        super().__init__(parent)
        self.setWindowTitle("FEM Mesh — Pendant Drop")
        self.resize(950, 800)
        self.setStyleSheet(DARK_STYLESHEET)

        self.points = points
        self.triangles = triangles
        self.boundary_edges = boundary_edges
        self.polygon = polygon
        self.metadata = metadata

        root = QVBoxLayout(self)
        root.setContentsMargins(12, 12, 12, 12)
        root.setSpacing(10)

        # ---- plot ----
        pg.setConfigOption('background', '#0f1018')
        pg.setConfigOption('foreground', '#c3c8dc')

        self.plot_widget = pg.PlotWidget(title="Pendant Drop Mesh")
        self.plot_widget.setLabel('bottom', 'r  (mm)')
        self.plot_widget.setLabel('left',   'z  (mm)')
        self.plot_widget.showGrid(x=True, y=True, alpha=0.12)
        self.plot_widget.setAspectLocked(True)
        self.plot_widget.invertY(True)
        root.addWidget(self.plot_widget, stretch=5)

        # ---- stats card ----
        stats_card = QFrame(objectName="card")
        stats_layout = QHBoxLayout(stats_card)
        stats_layout.setContentsMargins(14, 10, 14, 10)
        stats_layout.setSpacing(24)

        n_nodes = len(points)
        n_elem = len(triangles)
        n_bnd = len(boundary_edges) if boundary_edges is not None else 0

        areas = self._triangle_areas()
        min_area = areas.min() * 1e6   # mm²
        max_area = areas.max() * 1e6
        mean_area = areas.mean() * 1e6

        mesh_box = QGroupBox("Mesh statistics")
        mesh_vl = QVBoxLayout()
        mesh_text = (
            f"Nodes:           {n_nodes:,}\n"
            f"Triangles:       {n_elem:,}\n"
            f"Boundary edges:  {n_bnd:,}\n"
            f"─────────────────────\n"
            f"Min area:  {min_area:.4e} mm²\n"
            f"Max area:  {max_area:.4e} mm²\n"
            f"Mean area: {mean_area:.4e} mm²\n"
            f"Ratio max/min: {max_area / max(min_area, 1e-20):.1f}×"
        )
        lbl_mesh = QLabel(mesh_text)
        lbl_mesh.setStyleSheet(
            "color:#c3c8dc; font-family:'Consolas','Menlo',monospace; "
            "font-size:9.5pt;")
        mesh_vl.addWidget(lbl_mesh)
        mesh_box.setLayout(mesh_vl)
        stats_layout.addWidget(mesh_box, 1)

        dom_box = QGroupBox("Domain")
        dom_vl = QVBoxLayout()
        ri = metadata['r_inner_m'] * 1e3
        ro = metadata['r_outer_m'] * 1e3
        dom_text = (
            f"Needle ID:   {2*ri:.4f} mm\n"
            f"Needle OD:   {2*ro:.4f} mm\n"
            f"Neck height: {metadata['neck_height_m']*1e3:.4f} mm\n"
            f"Drop height: {metadata['drop_height_m']*1e3:.4f} mm"
        )
        lbl_dom = QLabel(dom_text)
        lbl_dom.setStyleSheet(
            "color:#c3c8dc; font-family:'Consolas','Menlo',monospace; "
            "font-size:9.5pt;")
        dom_vl.addWidget(lbl_dom)
        dom_box.setLayout(dom_vl)
        stats_layout.addWidget(dom_box, 1)

        root.addWidget(stats_card)

        # ---- draw ----
        self._draw_mesh()

    # ------------------------------------------------------------------
    def _triangle_areas(self):
        pts = self.points
        v0 = pts[self.triangles[:, 0]]
        v1 = pts[self.triangles[:, 1]]
        v2 = pts[self.triangles[:, 2]]
        cross = ((v1[:, 0] - v0[:, 0]) * (v2[:, 1] - v0[:, 1])
               - (v2[:, 0] - v0[:, 0]) * (v1[:, 1] - v0[:, 1]))
        return 0.5 * np.abs(cross)

    # ------------------------------------------------------------------
    def _triangles_to_lines(self, pts_mm):
        """Convert triangles to a single polyline with NaN separators."""
        tris = self.triangles
        n = len(tris)
        # v0 → v1 → v2 → v0, NaN
        xs = np.empty(n * 5)
        ys = np.empty(n * 5)
        for i, tri in enumerate(tris):
            v0, v1, v2 = pts_mm[tri]
            b = i * 5
            xs[b:b + 5] = [v0[0], v1[0], v2[0], v0[0], np.nan]
            ys[b:b + 5] = [v0[1], v1[1], v2[1], v0[1], np.nan]
        return xs, ys

    # ------------------------------------------------------------------
    def _draw_mesh(self):
        pw = self.plot_widget
        pts_mm = self.points * 1e3
        poly_mm = self.polygon * 1e3

        ri_mm = self.metadata['r_inner_m'] * 1e3
        ro_mm = self.metadata['r_outer_m'] * 1e3
        neck_h_mm = self.metadata['neck_height_m'] * 1e3

        # Needle wall hatching (both sides)
        for side in (+1, -1):
            pw.plot([side * ro_mm, side * ro_mm], [0, neck_h_mm],
                    pen=pg.mkPen(color=(200, 200, 200, 180), width=1.5))
            pw.plot([side * ri_mm, side * ro_mm], [0, 0],
                    pen=pg.mkPen(color=(200, 200, 200, 180), width=1.5))
            pw.plot([side * ri_mm, side * ro_mm],
                    [neck_h_mm, neck_h_mm],
                    pen=pg.mkPen(color=(200, 200, 200, 180), width=1.5))
            hx, hz = _hatch_rect(ri_mm, ro_mm, 0, neck_h_mm, n_lines=14)
            pw.plot(side * hx, hz,
                    pen=pg.mkPen(color=(180, 180, 180, 60), width=0.8))

        # Mesh triangles
        xs, ys = self._triangles_to_lines(pts_mm)
        pw.plot(xs, ys,
                pen=pg.mkPen(color=(200, 210, 230, 140), width=0.5),
                connect='finite')

        # Domain boundary outline
        pw.plot(poly_mm[:, 0], poly_mm[:, 1],
                pen=pg.mkPen(color=(100, 200, 255, 220), width=2.5))

        # Symmetry axis (visual only)
        z_range = [poly_mm[:, 1].min(), poly_mm[:, 1].max()]
        pw.plot([0, 0], z_range,
                pen=pg.mkPen(color=(90, 255, 140, 60), width=1,
                             style=Qt.PenStyle.DashDotLine))
